# Generated by Django 6.0.1 on 2026-03-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('feedback_received', 'Feedback Received'), ('goal_achieved', 'Goal Achieved'), ('coach_assigned', 'Coach Assigned'), ('message_received', 'Message Received'), ('report_reviewed', 'Report Reviewed'), ('performance_reminder', 'Performance Reminder')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('link_type', models.CharField(blank=True, help_text='Type of linked object (Feedback, Goal, Message, etc.)', max_length=50)),
                ('link_id', models.IntegerField(blank=True, help_text='ID of the linked object', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='api_notific_user_id_16328d_idx'), models.Index(fields=['user', 'created_at'], name='api_notific_user_id_d8a762_idx')],
            },
        ),
    ]
