# Generated by Django 5.2.8 on 2025-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach')], default='athlete', max_length=20),
        ),
    ]
