# Generated by Django 5.2.8 on 2026-03-17 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coachathleteassignment'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCapacityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('paused', 'Manually Paused'), ('resumed', 'Manually Resumed'), ('auto_paused', 'Auto-Paused (Capacity Reached)')], max_length=20)),
                ('athlete_count', models.IntegerField(help_text='Number of athletes at time of action')),
                ('reason', models.TextField(blank=True, help_text='Reason for pause/resume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from athlete to coach')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text="Coach's reason for rejection")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Auto-expire after 7 days')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When coach accepted/rejected', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coachathleteassignment',
            name='end_reason',
            field=models.TextField(blank=True, help_text='Reason for ending assignment'),
        ),
        migrations.AddField(
            model_name='coachathleteassignment',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachathleteassignment',
            name='ended_by',
            field=models.CharField(blank=True, choices=[('coach', 'Coach'), ('athlete', 'Athlete'), ('admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepting_requests',
            field=models.BooleanField(default=True, help_text='Whether coach is accepting new athlete requests'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_athletes',
            field=models.IntegerField(blank=True, help_text='Maximum number of athletes this coach can handle', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pause_reason',
            field=models.TextField(blank=True, help_text='Reason for pausing requests'),
        ),
        migrations.AddField(
            model_name='user',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When coach paused accepting requests', null=True),
        ),
        migrations.AlterField(
            model_name='coachathleteassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('accepting_requests', True), ('role', 'coach')), fields=['role', 'accepting_requests'], name='coach_accepting_idx'),
        ),
        migrations.AddField(
            model_name='coachcapacitylog',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='athlete',
            field=models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachathleteassignment',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Original request that created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='accounts.coachrequest'),
        ),
        migrations.AddIndex(
            model_name='coachcapacitylog',
            index=models.Index(fields=['coach', 'created_at'], name='accounts_co_coach_i_f54e59_idx'),
        ),
        migrations.AddIndex(
            model_name='coachrequest',
            index=models.Index(fields=['coach', 'status'], name='accounts_co_coach_i_725c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='coachrequest',
            index=models.Index(fields=['athlete', 'status'], name='accounts_co_athlete_002fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='coachrequest',
            index=models.Index(fields=['status', 'expires_at'], name='accounts_co_status_d07925_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('athlete', 'coach'), name='unique_pending_request'),
        ),
        migrations.AlterUniqueTogether(
            name='coachrequest',
            unique_together={('athlete', 'coach', 'status')},
        ),
    ]
