# Generated by Django

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fix_requested_at_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('height_unit', models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet')], default='cm', max_length=5)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=5)),
                ('body_type', models.CharField(choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph'), ('not_sure', 'Not Sure')], max_length=20)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], max_length=20)),
                ('primary_sport', models.CharField(max_length=100)),
                ('years_training', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_performance_baseline', models.TextField()),
                ('primary_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('speed', 'Speed'), ('flexibility', 'Flexibility'), ('general_fitness', 'General Fitness')], max_length=20)),
                ('goal_timeframe', models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('ongoing', 'Ongoing')], max_length=20)),
                ('target_event', models.CharField(blank=True, max_length=200)),
                ('target_event_date', models.DateField(blank=True, null=True)),
                ('weekly_availability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('preferred_intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('varied', 'Varied')], max_length=20)),
                ('preferred_training_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('flexible', 'Flexible')], max_length=20)),
                ('equipment_access', models.JSONField(default=list)),
                ('injury_history', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('current_activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extremely_active', 'Extremely Active')], max_length=20)),
                ('motivation_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guidance_preference', models.CharField(choices=[('self_directed', 'Self Directed'), ('structured_plan', 'Structured Plan'), ('coach_guided', 'Coach Guided')], max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='athleteprofile',
            index=models.Index(fields=['user'], name='accounts_ath_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteprofile',
            index=models.Index(fields=['fitness_level'], name='accounts_ath_fitness_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteprofile',
            index=models.Index(fields=['primary_goal'], name='accounts_ath_primary_idx'),
        ),
    ]
