# Generated by Django 5.2.8 on 2026-05-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RenameField(
            model_name='coachrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RenameIndex(
            model_name='athleteprofile',
            new_name='accounts_at_user_id_e0114f_idx',
            old_name='accounts_ath_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='athleteprofile',
            new_name='accounts_at_fitness_2870f4_idx',
            old_name='accounts_ath_fitness_idx',
        ),
        migrations.RenameIndex(
            model_name='athleteprofile',
            new_name='accounts_at_primary_89417f_idx',
            old_name='accounts_ath_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='accounts_us_user_id_506163_idx',
            old_name='accounts_us_user_id_5e8b9a_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='accounts_us_action__4b1ffb_idx',
            old_name='accounts_us_action__7c4f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='accounts_us_created_f371fd_idx',
            old_name='accounts_us_created_3f2a1b_idx',
        ),
    ]
