# Generated by Django 6.0.1 on 2026-02-02 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('level', models.CharField(default='general', help_text='e.g., U18, U20, Elite', max_length=50)),
                ('benchmark_value', models.FloatField(help_text='e.g., 4.6 for 40m sprint in seconds')),
                ('unit', models.CharField(default='seconds', help_text='seconds, meters, etc', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='e.g., 40m Sprint', max_length=100)),
                ('target_value', models.FloatField(help_text='e.g., 4.5')),
                ('current_value', models.FloatField(default=0.0, help_text='Best/latest performance')),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('benchmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='performance.benchmark')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='e.g., 40m Sprint', max_length=100)),
                ('value', models.FloatField(help_text='e.g., 4.9 seconds')),
                ('intensity', models.IntegerField(default=5, help_text='1-10 scale')),
                ('notes', models.TextField(blank=True)),
                ('date_logged', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
