# Generated by Django 6.0.1 on 2026-02-20 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_benchmark_options_alter_goal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancelog',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='performancelog',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='performancelog',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='performancelog',
            name='power',
        ),
        migrations.CreateModel(
            name='CoachFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('performance', 'Performance Review'), ('goal', 'Goal-Specific'), ('technique', 'Technique Improvement'), ('motivation', 'Motivational')], default='general', max_length=20)),
                ('title', models.CharField(help_text='Brief title for the feedback', max_length=200)),
                ('message', models.TextField(help_text='Detailed feedback message')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='performance.goal')),
                ('performance_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='performance.performancelog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['athlete', 'is_read'], name='performance_athlete_66e72b_idx'), models.Index(fields=['coach', 'created_at'], name='performance_coach_i_fc0d55_idx')],
            },
        ),
    ]
