# Generated by Django 6.0.1 on 2026-03-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_remove_performancelog_elevation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancelog',
            name='how_felt',
            field=models.CharField(choices=[('great', '😊 Felt Great'), ('good', '🙂 Felt Good'), ('okay', '😐 Felt Okay'), ('tired', '😓 Felt Tired'), ('struggled', '😰 Struggled')], default='good', help_text='Overall feeling during workout', max_length=20),
        ),
        migrations.AddField(
            model_name='performancelog',
            name='intensity_level',
            field=models.CharField(choices=[('easy', 'Easy Recovery'), ('moderate', 'Steady'), ('hard', 'Challenging'), ('race', 'Maximum Effort')], default='moderate', help_text='How hard was this workout?', max_length=20),
        ),
        migrations.AddField(
            model_name='performancelog',
            name='perceived_effort',
            field=models.IntegerField(default=5, help_text='How hard did this feel? 1=very easy, 10=maximum'),
        ),
        migrations.AddField(
            model_name='performancelog',
            name='terrain',
            field=models.CharField(blank=True, help_text='flat, hilly, trail, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='performancelog',
            name='weather',
            field=models.CharField(blank=True, help_text='hot, cold, rainy, etc.', max_length=50, null=True),
        ),
    ]
