# Generated by Django 6.0.1 on 2026-03-01 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_performancelog_how_felt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('deadline_weeks', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('conservative', 'Conservative'), ('recommended', 'Recommended'), ('ambitious', 'Ambitious')], default='recommended', max_length=20)),
                ('reasoning', models.TextField()),
                ('training_required', models.CharField(max_length=100)),
                ('key_tip', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Waiting for Decision'), ('accepted', 'Accepted by Athlete'), ('rejected', 'Rejected by Athlete')], default='pending', max_length=20)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('actual_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_source', to='performance.goal')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-suggested_at'],
                'indexes': [models.Index(fields=['athlete', 'status'], name='performance_athlete_872dcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuggestedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('speed', 'Speed Work'), ('endurance', 'Endurance'), ('intervals', 'Intervals'), ('recovery', 'Recovery')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_unit', models.CharField(max_length=50)),
                ('intensity', models.CharField(max_length=20)),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('reasoning', models.TextField()),
                ('benefit', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('added_to_plan', 'Added to Training Plan'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='suggested', max_length=20)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_source', to='performance.performancelog')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-suggested_at'],
                'indexes': [models.Index(fields=['athlete', 'status'], name='performance_athlete_99ef34_idx')],
            },
        ),
    ]
