# Generated by Django 6.0.1 on 2026-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_suggestedgoal_suggestedworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedgoal',
            name='training_required',
            field=models.TextField(),
        ),
    ]
