# Generated by Django 6.0.1 on 2026-03-06 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_alter_suggestedgoal_training_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Message subject', max_length=200)),
                ('body', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the message was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('parent_message', models.ForeignKey(blank=True, help_text='Parent message if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='performance.message')),
                ('recipient', models.ForeignKey(help_text='User who receives the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='performance_sender__d0c523_idx'), models.Index(fields=['recipient', 'is_read'], name='performance_recipie_92764a_idx')],
            },
        ),
    ]
