# Generated by Django 6.0.1 on 2026-03-06 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Report title', max_length=200)),
                ('time_range', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=20)),
                ('analytics_data', models.JSONField(help_text='Performance analytics data')),
                ('athlete_notes', models.TextField(blank=True, help_text="Athlete's comments about their performance")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('feedback_given', 'Feedback Given')], default='pending', max_length=20)),
                ('coach_feedback', models.TextField(blank=True, help_text="Coach's feedback on the report")),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the coach reviewed the report', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the report was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(help_text='Athlete who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(help_text='Coach who receives the report', on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['athlete', 'submitted_at'], name='performance_athlete_50be54_idx'), models.Index(fields=['coach', 'status'], name='performance_coach_i_a4388a_idx')],
            },
        ),
    ]
