# Generated by Django 6.0.1 on 2026-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_performancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachfeedback',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachfeedback',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
